repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=1000']
    -   id: check-ast
    -   id: check-json
    -   id: check-toml
    -   id: detect-private-key
    -   id: mixed-line-ending
        args: ['--fix=lf']
    -   id: debug-statements

-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        language_version: python3.10

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.254'
    hooks:
    -   id: ruff
        args: [
            '--fix',
            '--select=E,F,I,N,UP,B,A,C4,SIM,ERA,PL',
            '--exit-non-zero-on-fix'
        ]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
    -   id: mypy
        additional_dependencies: [
            'types-requests',
            'numpy>=1.24.0',
            'polars>=0.18.0',
            'scipy>=1.10.0'
        ]
        exclude: ^(docs/|tests/)

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black"]

-   repo: https://github.com/mgedmin/check-manifest
    rev: "0.49"
    hooks:
    -   id: check-manifest
        stages: [manual]

-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
    -   id: nbqa-black
        additional_dependencies: [black==23.1.0]
        files: ^notebooks/.*\.ipynb$
    -   id: nbqa-isort
        additional_dependencies: [isort==5.12.0]
        files: ^notebooks/.*\.ipynb$