[project]
name = "ThermogramForge"
version = "0.1.0"
description = "Python implementation of thermogram analysis tools"
authors = [
    {name = "Karl Reger", email = "karl.reger@example.com"}
]
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "polars>=0.18.0",
    "numpy>=1.24.0",
    "scipy>=1.10.0",
    "dash>=2.9.0",
    "plotly>=5.14.0",
    "statsmodels>=0.14.0",
    "rich>=13.0.0",
]

[project.optional-dependencies]
r-integration = [
    "rpy2>=3.5.0",
]
export = [
    "kaleido>=0.2.1",  # For static image export in Plotly
]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "mypy>=1.0.0",
    "ruff>=0.0.1",
    "black>=23.0.0",
    "sphinx>=7.0.0",
    "sphinx_rtd_theme>=1.2.0",
    "pyinstaller>=5.13.0",
]
full = [
    "rpy2>=3.5.0",
    "kaleido>=0.2.1",
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "mypy>=1.0.0",
    "ruff>=0.0.1", 
    "black>=23.0.0",
    "sphinx>=7.0.0",
    "sphinx_rtd_theme>=1.2.0",
    "pyinstaller>=5.13.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 88
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.black]
line-length = 88
target-version = ["py310"]

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true

[tool.hatch.build.targets.wheel]
packages = [
    "thermogram_baseline",
    "thermogram_app",
    "tlbparam"
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"

[dependency-groups]
dev = [
    "black>=25.1.0",
    "mypy>=1.15.0",
    "pytest>=8.3.5",
    "pytest-cov>=6.0.0",
    "ruff>=0.9.10",
    "sphinx>=8.1.3",
    "sphinx_rtd_theme>=1.2.0",
    "pyinstaller>=5.13.0",
]
r-integration = [
    "rpy2>=3.5.0",
]
export = [
    "kaleido>=0.2.1",
]

[project.scripts]
ThermogramForge = "thermogram_app.app:app.run_server"