[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "thermogramforge"
version = "0.1.0"
description = "Python toolkit for thermogram analysis"
readme = "README.md"
requires-python = ">=3.12"
license = {file = "LICENSE"}
authors = [
    {name = "Karl Reger", email = "kcr28@nau.edu"}
]
maintainers = [
    {name = "Karl Reger", email = "kcr28@nau.edu"}
]
keywords = ["thermogram", "dsc", "thermal analysis", "biophysics"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
]

dependencies = [
    "polars>=0.19.0",
    "dash>=2.14.0",
    "plotly>=5.18.0",
    "flask>=3.0.0",
    "numpy>=1.26.0",
    "scipy>=1.12.0",
    "numba>=0.58.0",
    "thermogram_baseline @ file://./packages/thermogram_baseline",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
    "pytest-cov>=4.1.0",
    "black>=23.7.0",
    "isort>=5.12.0",
    "mypy>=1.5.0",
    "ruff>=0.0.280",
    "sphinx>=7.1.1",
    "sphinx-rtd-theme>=1.3.0",
]

[tool.black]
line-length = 88
target-version = ["py312"]

[tool.isort]
profile = "black"
line_length = 88

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["packages"]