from typing import Any

# This is a minimal stub file for plotly to satisfy type checking

class Figure:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_trace(self, trace: Any, row: int = ..., col: int = ...) -> None: ...
    def update_layout(self, **kwargs: Any) -> None: ...
    def update_xaxes(self, **kwargs: Any) -> None: ...
    def update_yaxes(self, **kwargs: Any) -> None: ...
    def add_vline(self, **kwargs: Any) -> None: ...
    def add_hline(self, **kwargs: Any) -> None: ...
    def add_shape(self, **kwargs: Any) -> None: ...
    def add_annotation(self, **kwargs: Any) -> None: ...
    def show(self) -> None: ...
    def write_html(self, file_path: str) -> None: ...
    def write_image(self, file_path: str, **kwargs: Any) -> None: ...
