from typing import Any, Dict, Optional

# This is a minimal stub file for plotly.graph_objects to satisfy type checking

class Figure:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_trace(self, trace: Any, row: int = ..., col: int = ...) -> None: ...
    def update_layout(self, **kwargs: Any) -> None: ...
    def update_xaxes(self, **kwargs: Any) -> None: ...
    def update_yaxes(self, **kwargs: Any) -> None: ...
    def add_vline(self, **kwargs: Any) -> None: ...
    def add_hline(self, **kwargs: Any) -> None: ...
    def add_shape(self, **kwargs: Any) -> None: ...
    def add_annotation(self, **kwargs: Any) -> None: ...
    def show(self) -> None: ...
    def write_html(self, file_path: str) -> None: ...
    def write_image(self, file_path: str, **kwargs: Any) -> None: ...

class Scatter:
    def __init__(
        self,
        x: Optional[Any] = None,
        y: Optional[Any] = None,
        mode: Optional[str] = None,
        name: Optional[str] = None,
        marker: Optional[Dict[str, Any]] = None,
        line: Optional[Dict[str, Any]] = None,
        **kwargs: Any,
    ) -> None: ...
