[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "thermogram_baseline"
version = "0.1.0"
description = "Thermogram baseline detection and subtraction"
readme = "README.md"
requires-python = ">=3.12"
license = {file = "../../LICENSE"}
authors = [
    {name = "Karl Reger", email = "kcr28@nau.edu"},
    {name = "Keegan Line", email = "ktl56@nau.edu"}
]

dependencies = [
    "polars>=0.19.0",
    "numpy>=1.26.0",
    "scipy>=1.12.0",
    "numba>=0.58.0",
    "plotly>=5.18.0",
    "statsmodels>=0.14.0",
]