[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tlbparam"
version = "0.1.0"
description = "Thermogram parameter calculation and analysis"
readme = "README.md"
requires-python = ">=3.12"
license = {file = "../../LICENSE"}
authors = [
    {name = "Karl Reger", email = "kcr28@nau.edu"}
]

dependencies = [
    "polars>=0.19.0",
    "numpy>=1.26.0",
    "scipy>=1.12.0",
    "plotly>=5.18.0",
]