name: ThermogramForge CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    # Install UV before setting up virtual environment
    - name: Install UV
      run: |
        pip install uv

    # Cache UV virtual environment for faster builds
    - name: Cache UV virtual environment
      uses: actions/cache@v3
      with:
        path: .uv
        key: uv-venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          uv-venv-${{ runner.os }}-${{ matrix.python-version }}-

    # Create virtual environment using UV
    - name: Create virtual environment
      run: |
        uv venv

    # Ensure local package path is correctly referenced in pyproject.toml
    - name: Fix local package path for Hatch
      run: |
        sed -i "s|file:///absolute/path/will/be/injected|file://$(pwd)/packages/thermogram_baseline|g" pyproject.toml

    # Install dependencies using UV
    - name: Install dependencies
      run: |
        uv pip install -e ".[dev]"

    # Debug: Verify installed packages
    - name: List installed packages
      run: |
        uv pip list

    # Run Ruff for linting
    - name: Lint with Ruff
      run: |
        uv pip ruff check .

    # Run Mypy for type checking
    - name: Type check with Mypy
      run: |
        uv pip mypy --install-types --non-interactive .

    # Run tests with pytest
    - name: Test with pytest
      run: |
        uv pip pytest --cov=thermogram_baseline --cov-report=xml

    # Upload test coverage report
    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false