name: ThermogramForge CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12]  # Reduced to most relevant versions

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install UV and create virtual environment
      run: |
        pip install uv
        uv venv
        
    - name: Install dependencies
      run: |
        source .venv/bin/activate
        uv pip install pytest pytest-cov ruff mypy
        uv pip install -e packages/thermogram_baseline
        
    - name: Lint with ruff
      run: |
        source .venv/bin/activate
        # Execute ruff with the full path to ensure it's found
        python -m ruff check .
        
    - name: Type check with mypy
      run: |
        source .venv/bin/activate
        # Execute mypy with the full path to ensure it's found
        python -m mypy --install-types --non-interactive .
        
    - name: Test with pytest
      run: |
        source .venv/bin/activate
        python -m pytest --cov=packages/thermogram_baseline --cov-report=xml
        
    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false