name: ThermogramForge CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    # Install UV before setting up virtual environment
    - name: Install UV
      run: |
        pip install uv

    # Create virtual environment using UV
    - name: Create virtual environment
      run: |
        uv venv

    # Install dependencies using UV
    - name: Install dependencies
      run: |
        uv pip install -e ".[dev]"

    # Debug: Verify installed packages
    - name: List installed packages
      run: |
        uv pip list

    # Run Ruff for linting
    - name: Lint with Ruff
      run: |
        uv run ruff check .

    # Run Mypy for type checking
    - name: Type check with Mypy
      run: |
        uv run mypy --install-types --non-interactive packages/

    # Run tests with pytest
    - name: Test with pytest
      run: |
        uv run pytest --cov=thermogram_baseline --cov-report=xml

    # Upload test coverage report
    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
